config/routes.rb
Rails.application.routes.draw do

  resources :shows do
    resources :beacons
  end

  get :visits, to: 'visits#index'
  post :visits, to: 'visits#create'

  resources :products

  root to: "shows#index"

end

app/models/beacon.rb
class Beacon < ActiveRecord::Base
  belongs_to :show
  has_many :products, dependent: :destroy

  def as_json(options={})
    super(:include => [:products])
  end
end

app/models/datum.rb
class Datum < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "1002x855>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :beacon

  def image_url
    image.url(:medium)
  end

end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :beacons, dependent: :destroy

  def as_json(options={})
      super(
        include: {beacons: {
          :methods =>[:image_url],
            include: :products}})
  end

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :beacon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController

  respond_to :json

  def index
    @products = Product.all
  end

  def new
    @show = Show.find(params[:show_id])
    @beacon = Beacon.new
    @beacons = @show.beacons
    @beacon_list = Beacon.all
  end

  def create
    show = Show.find(params[:show_id])
    show.beacons.create(beacon_params)
    flash[:notice] = "Beacon successfully added"
    redirect_to new_show_beacon_path(show)
  end

  def destroy
    show = Show.find(params[:show_id])
    beacon = Beacon.find(params[:id])
    beacon.destroy
    flash[:notice] = 'Beacon deleted successfully'
    redirect_to new_show_beacon_path
  end

  def show
    @products = Product.all
  end

  def beacon_params
    params.require(:beacon).permit(:name, :major, :minor, :show_id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
  end

  def index
    @products = Product.all
  end

  def create
    Product.create(product_param)
    flash[:notice] = "Product successfully added"
    redirect_to new_product_path()
  end

  def edit
     @product = Product.find(params[:id])
     @beacon = Beacon.all
  end

  def update
    # @beacon = Beacon.find(params[:id])
    @product = Product.find(params[:id])
    # @product.update(product_beacon_param)
    @product.update(product_url_param)
    flash[:notice] = "Product added to Beacon"
    redirect_to '/'
  end

  def show
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    flash[:notice] = 'Product deleted successfully'
    redirect_to new_product_path
  end

  def product_param
    params.require(:product).permit(:name, :price, :owner, :image)
  end

  def product_beacon_param
    params.require(:beacon).permit(:beacon_id)
  end

  def product_url_param
    params.require(:product).permit(:url, :beacon_id)
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  def new
    @show = Show.new
    @show_all = Show.all
  end

  def index
    @shows = Show.all
  end

  def create
    Show.create(show_params)
    flash[:notice] = "Show successfully added"
    redirect_to shows_path
  end

  def show_params
    params.require(:show).permit(:name, :location)
  end

  def show
    @show = Show.find params[:id]
    respond_to do |format|
      format.json do
        render json: @show, :callback => params['callback'], :content_type => 'application/javascript'
      end
    end
  end

  def destroy
    @show= Show.find(params[:id])
    @show.destroy
    flash[:notice] = 'Show deleted successfully'
    redirect_to shows_path
  end

  def new_beacon
   @show = Show.find params[:show_id]
   redirect_to new_show_beacon_path @show
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  skip_before_filter  :verify_authenticity_token

  def create
    Visit.create visit_params
  end

  def visit_params
    params.require(:visit).permit(:beacon_id, :timestamp)
  end

  def index
    @visits = Visit.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beacons_helper.rb
module BeaconsHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/beacons/index.erb
No Beacons listed

<%=link_to "Add Beacon", new_beacon_path() %>

app/views/beacons/index.html.erb
<h2 class=productList align="center">Product to Beacon Assignment</h2>
<div align="center">
<%@products.each do |product|%>
  <li>
    <%= product.owner%>:
    <%= link_to product.name, edit_product_path(product) %>
    <%= product.beacon_id%>
  </li>
<%end%>
</div>

app/views/beacons/new.erb
<%=form_for Beacon.new do |f|%>
  <%=f.label :name%>
  <%= f.text_field :name%>
  <%=f.label :major%>
  <%= f.text_field :major%>
  <%=f.label :minor%>
  <%= f.text_field :minor%>
  <%= f.submit "Add Beacon"%>
<%end%>

app/views/beacons/new.html.erb
<div align="center">
<%=form_for [@show, @beacon] do |f|%>
  <%= f.label :name%>
  <%= f.text_field :name%>
  <%= f.label :major%>
  <%= f.text_field :major%>
  <%= f.label :minor%>
  <%= f.text_field :minor%>
  <%= f.submit "Add Beacon"%>
<%end%>
</div>
<div align="center">
<h2 class=tableHeading> Avaliable Beacons</h2>
<%=link_to "Assign Products", show_beacons_path()%>
<%if @beacons.any?%>
  <table>
    <tr>
      <th>Name</th>
      <th>Major</th>
      <th>Minor</th>
    </tr>

    <%@beacons.each do |beacon|%>

    <tr>
      <td><%=beacon.name%></td>
      <td><%=beacon.major%></td>
      <td><%=beacon.minor%></td>
      <!-- <td><%= link_to "Delete", show_beacons_path(beacon), method: :delete %></td> -->
    </tr>

    <%end%>
  </table>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProximibeeAdmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="./assets/stylesheets/main.css">
</head>
<header>

</header>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand" style="display:inline-flex">
        <div id="logoimg">
          <%=link_to image_tag('logo.png',  size: "50"), root_path, method: :get%>
        </div>
        <div id="logopro">
        PROXIMIBEE
        </div>
      </div>
    </div>
  </nav>

<%= notice%>
<main>
  <%= yield %>
</main>

</body>
</html>
<footer>
</footer>

app/views/products/edit.html.erb
<div align="center">
<%= form_for @product do |f| %>
  <%=f.label :beacon_id %>
  <%=f.text_field :beacon_id%>
  <%=f.label :url%>
  <%=f.text_field :url, :value => @product.image.url(:medium)%>
  <%=f.submit %>
<% end %>

<%if @beacon.any?%>
  <%@beacon.each do |beacon|%>
  <br>
  <li>
    <%=beacon.name%>
    <%=beacon.id%>
  </li>
  <%end%>
<%end%>
</div>

app/views/products/index.html.erb
<%if Product.all.any?%>
  <table class="fixed_headers">
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Beacon</th>
    </tr>
    <%Product.all.each do |product|%>
    <tr>
      <td><%=product.name%></td>
      <td><%=product.price%></td>
    </tr>
    <%end%>
  </table>
<%end%>

app/views/products/new.html.erb
<div align="center">
<%=form_for Product.new, html: {multipart: true}  do |f|%>
  <%=f.label :owner%>
  <%=f.text_field :owner%>
  <%=f.label :name%>
  <%=f.text_field :name%>
  <%=f.label :price%>
  <%=f.text_field :price%>
  <%=f.file_field :image%>
  <%=f.submit "Add Product" %>
<%end%>
</div>
<main>
  <%if Product.all.any?%>
  <div align="center">
  <br><br><br><br>
    <table class="fixed_headers">
      <tr>
        <th>Owner</th>
        <th>Product</th>
        <th>Price</th>
        <th>Image</th>
        <th>Delete</th>
      </tr>
      <%Product.all.each do |product|%>
      <tr>
        <td><%=product.owner%></td>
        <td><%=product.name%></td>
        <td><%=product.price%></td>
        <td><%= image_tag product.image.url(:thumb) %></td>
        <td><%= link_to "Delete", product_path(product), method: :delete %></td>
      </tr>
      <%end%>
    </table>
    </div>
  <%end%>
</main>

app/views/shows/index.html.erb
<main>

<h1 align="center">Options</h1>

<div class="shows">

  <%=link_to image_tag('calendar.png'), new_show_path() %>

  <%=link_to image_tag('product.png'), new_product_path() %>

  <%=link_to image_tag('graph.png'), visits_path() %>
</div>
<div class="or-spacer2">
  <div class="mask2"></div>
</div>
    <% if @shows.any? %>
   <h1 align="center" style="margin-bottom:50px;">Collections</h1>
    <%@shows.each do |show|%>

      <h3 align="center"><%=link_to show.name, new_show_beacon_path(show)%></h3>
    <%end%>
  <%end%>
</main>

app/views/shows/new.html.erb
<div id="content">
<h1 style="margin-left:120px;">Add a show</h1>
<%=form_for Show.new do |f|%>
  <%= f.label :name%>
  <%= f.text_field :name%>
  <%= f.label :location%>
  <%= f.text_field :location%>
  <%= f.submit "Add Show"%>
<%end%>
</div>

<div class="or-spacer-vertical right">
  <div class="mask"></div>
</div>


<div id="sidebar">
<% if @show_all.any? %>
 <h1 style="margin-left:-10px;">List of shows</h1>
  <%@show_all.each do |show|%>
  <li>
    <%=link_to show.name, new_show_beacon_path(show)%>
    <%= link_to "Delete", show_path(show), method: :delete %>
    </li>
  <%end%>
<%end%>
</div>

app/views/visits/index.html.erb
<head>
  <meta http-equiv="refresh" content="5" />
</head>

<main>
<div align="center">
 <% if @visits.any? %>
   <h2>Visits</h2>
    <%@visits.reverse.each do |visit|%>

    <li>
      <h3>Beacon <%=visit.beacon.name%> was visited at <%=visit.created_at%></h3>
    </li>
    <%end%>
  <%end%>
</div>
</main>